VALUE INFERENCE BNF


#https://datatagginglibrary.readthedocs.io/en/latest/tutorial/inference.html#adding-inferres-to-a-model
<value_inference> 				::= <value_inferrer>*

<value_inferrer>				::= "[" <slot_identifier> ":" "support" <inference_pair>* "]"

<inference_pair>				::= "[" <assignment_slot> (";" <assignment_slot>)* "->" <identifier_simple> "]"

<assignment_slot> 				::= (<atomic_assignment_slot> | <aggregate_assignment_slot>)

<atomic_assignment_slot> 		::= <slot_identifier> "=" <identifier_simple>

<aggregate_assignment_slot> 	::= <slot_identifier> "+=" <identifier_simple>

<slot_identifier> 				::= <identifier_simple> ("/" <identifier_simple>)*

<identifier_simple>				::= legal slot/value name


#COMMENTS

<line_comment>					::= "<--" 

<multi_line_comment>			::= "<*" <free_text> (<newline> [<free_text>])* "*>"

